### PR TITLE
Fill the "Alternate App Icon Sets" build settings

### PR DESCRIPTION
**Pull request by cs-altshift**
In order to make Product Page Optimization working, we need this other build setting to be filled. I think it should not interfere with any other usage you had before.

### CODE REVIEW

**Comment by kyubuns** [comment]
Thanks for the PR!
I'm sorry, but I don't have the environment to check Product Page Optimization and I don't think I'll be able to merge it soon.
If anyone has had this work properly, please comment.

**Comment by cs-altshift** [comment]
No problem. We are working with the fork for now. Soon I will be able to validate the process for PPO and give you a feedback on how it went.

**Comment by cs-altshift** [comment]
This code is not working in fact. I've used the wrong parameter. So I reject my own PR :)

**Comment by cs-altshift** [comment]
I am so sorry. My previous message was a mistake as we wrongly thought the alternate icons were missing on App Store Connect. This code is OK per our testing.

**Comment by Andreyul** [comment]
What is the point of including "ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES" if there is already "ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS"?

**Comment by cs-altshift** [comment]
To be honest, with further review, it may indeed be useless. I've done a lot of tests with App Store Connect and it seemed the only way to make Product Page Optimization working was with this setting filled. But that may be totally coincidental.

**Comment by kyubuns** [comment]
Thank you for your patience.
I have confirmed and will merge it!

**Pull request merged**
